### ISSUE TITLE
Use core-js instead of @babel/polyfill

### ISSUE THREAD

**Issue by jtiala** [jtiala/reducks-starter#18]
@babel/polyfill is deprecated.

![Screenshot 2019-09-05 at 13 29 18](https://user-images.githubusercontent.com/1576782/64334601-8952b180-cfe1-11e9-9b2f-11fe614b48bf.png)

**Comment by arturparkhisenko** [comment]
@jtiala can I try to handle that? Hacktoberfest)

**Comment by jtiala** [comment]
Sure! Thanks.
