### ISSUE TITLE
Create GraphQL middleware

### ISSUE THREAD

**Issue by jtiala** [jtiala/reducks-starter#2]
In the same style the rest middleware is working. Better desciption coming soon™️

**Comment by klshriharsha** [comment]
Do you prefer any specific GraphQL client? Apollo is one of the most popular GraphQL clients. I could try integrating that as a middleware.

**Comment by jtiala** [comment]
Yeah, Apollo is fine. If you're gonna work in this, try to duplicate the mocking logic found in rest middelware :)
