### ISSUE TITLE
Write proper README

### ISSUE THREAD

**Issue by jtiala** [jtiala/reducks-starter#4]

**Comment by bashbers** [comment]
I'll look into this. But whenever you're gonna make a new issue, please post more information than just the title. Some of these other issues are vague.

**Comment by jtiala** [comment]
Yes, agreed and apologies. I didn't anticipate that people would this eager to work on the project :) I shouldn't have added the hacktober labels before writing descriptions first.

For starters, we could add listing of the features and reasoning behind them, quick start guide, contributing guidelines (@sidhyatikku already added some in the PR above) and maybe something about the structure.

**Comment by sidhyatikku** [comment]
Given the limited information about the project, I tried my best to add some commits. @jtiala can you give a short description ?

**Comment by jtiala** [comment]
Thanks for your contributions, both of you. I merged them. I'll take care of the rest of the README later. Sorry again for not having any description.
